name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package to Github Package
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Export Password
        run: |
          echo "" >> gradle.properties
          echo signing.keyId=$SIGN_KEY_ID >> gradle.properties
          echo signing.password=$SIGN_PWD >> gradle.properties
          base64 -d <<< "$SIGN_KEY" > ./pgp.key
          echo signing.secretKeyRingFile=$PWD/pgp.key >> gradle.properties
        env:
          SIGN_KEY_ID: ${{ secrets.SIGN_KEY_ID }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_PWD: ${{ secrets.SIGN_PWD }}
      - name: Publish package to Maven Central
        run: gradle uploadArchives
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
